// templates/Angular2Spa/ClientApp/app/components/counter/counter.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'counter',
    templateUrl: './counter.component.html'
})
export class CounterComponent {
    public currentCount = 0;

    public incrementCounter() {
        this.currentCount++;
    }
}

<h1>Counter</h1>

<p>This is a simple example of an Angular 2 component.</p>

<p>Current count: <strong>{{ currentCount }}</strong></p>

<button (click)="incrementCounter()">Increment</button>

// templates/ReactSpa/ClientApp/components/Counter.tsx
import * as React from 'react';

interface CounterState {
    currentCount: number;
}

export class Counter extends React.Component<any, CounterState> {
    constructor() {
        super();
        this.state = { currentCount: 0 };
    }
    
    public render() {
        return <div>
            <h1>Counter</h1>
            
            <p>This is a simple example of a React component.</p>

            <p>Current count: <strong>{ this.state.currentCount }</strong></p>
            
            <button onClick={ () => { this.incrementCounter() } }>Increment</button>
        </div>;
    }
    
    incrementCounter() {
        this.setState({
            currentCount: this.state.currentCount + 1
        });
    }
}
